# Generated by Django 4.2.4 on 2023-08-06 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todoitem_completed_date_todoitem_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['is_completed', 'due_date']},
        ),
    ]
