# Generated by Django 4.2.4 on 2023-08-06 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0004_todoitem_owner_todolist_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='todolist',
            unique_together={('title', 'owner')},
        ),
    ]
